#注意：记事本编写 不要用table键，用两个空格键
spring:
  profiles:
    active: dev #激活开发环境配置
---
server:
  port: 4001 #端口号
spring:
  profiles: dev  #开发环境
  applicatons:
    name: microservice-config-dev
---
server:
  port: 4002
spring:
  profiles: prod #生产环境
  applicatons:
    name: microservice-config-prod 